name: Continuous Integration
on:
  push:
    paths:
      - Cargo.lock
      - Cargo.toml
      - resources/assets/*.ttf
      - src/**
  pull_request:
    paths:
      - Cargo.lock
      - Cargo.toml
      - resources/assets/*.ttf
      - src/**

jobs:
  lint:
    name: lint
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        lint: [check, test, clippy, fmt]
        exclude: # https://github.com/community/community/discussions/7835
          - os: windows-latest
            lint: clippy
          - os: windows-latest
            lint: fmt
          - os: macOS-latest
            lint: clippy
          - os: macOS-latest
            lint: fmt
        include:
          - lint: check
            args: " --all-features"
          - lint: test
            args: ""
          - lint: clippy
            args: " --all --all-features -- -D warnings"
          - lint: fmt
            args: " --all -- --check"
    steps:
      - uses: actions/checkout@v4
      - uses: rui314/setup-mold@v1 # faster linker
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target
          key: ${{ runner.os }}-${{ matrix.lint }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.OS }}-${{ matrix.lint }}-
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy,rustfmt
      - run: cargo ${{ matrix.lint }}${{ matrix.args }}

  coverage:
    name: coverage
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Download grcov
        run: |
          mkdir -p "${HOME}/.local/bin"
          curl -sL https://github.com/mozilla/grcov/releases/download/v0.8.19/grcov-x86_64-unknown-linux-gnu.tar.bz2 | tar jxf - -C "${HOME}/.local/bin"
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Set up DeepSource CLI
        run: curl https://deepsource.io/cli | sh
      - name: Install LLVM-profdata
        run: rustup component add llvm-tools-preview
      - name: Run tests
        run: CARGO_INCREMENTAL=0 RUSTFLAGS='-Cinstrument-coverage' LLVM_PROFILE_FILE='cargo-test-%p-%m.profraw' cargo test
      - name: Run GRCOV
        run: grcov . --binary-path ./target/debug/deps/ -s . -t lcov --branch --ignore-not-existing --ignore '../*' --ignore "/*" -o target/coverage/tests.lcov
      - name: Upload to DeepSource
        env:
          DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
        run: ./bin/deepsource report --analyzer test-coverage --key rust --value-file target/coverage/tests.lcov